send email via mailgun api.
bmarsh9/spate-operators pull request #1
Opened 2022-11-03 14:47 UTC by felixguerrero12

This pull request is submitted to add email via mailgun api. Beautified the manifest.json file, and added the mailgun section as 008.

2022-11-03 20:33 UTC, felixguerrero12 commented
This code will need to be modified to call from the locker or even the environment variable. The goal is to have a static e-mail service to enable the administrator send e-mails using api.

2022-11-04 16:56 UTC, felixguerrero12 commented
I am a shit git user. This includes both the s3, and mailgun. going to see if I can fix this up.

2022-11-10 23:47 UTC, bmarsh9 commented on operators/s3.py
> +    out.list_buckets()
Unfortunately Spate won't be able to support this format. Your other operator [here](https://github.com/bmarsh9/spate-operators/pull/1/files#diff-aee348fe6b9fac5e95a99a0a0a5f6cf59b4225bf3c0cc45099fb862d733f5489) is the correct format

2022-11-10 23:50 UTC, bmarsh9 requested changes
Everything looks good except for the format in [s3.py](https://github.com/bmarsh9/spate-operators/pull/1/files#diff-2ac2fb13e9512b5e973588472978a2a73bd348854e78b3455fb773cf14e92c0e)

2023-10-03 02:12 UTC, closed without merging